apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - authclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - authclients/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - authclients/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - auths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - auths/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - auths/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - benthos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - benthos/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - benthos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - benthosstreams
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - benthosstreams/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - benthosstreams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - brokerconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - brokerconsumers/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - brokerconsumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - brokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - brokers/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - brokers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - brokertopics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - brokertopics/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - brokertopics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - databases/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - databases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - gatewayhttpapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - gatewayhttpapis/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - gatewayhttpapis/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - ledgers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - ledgers/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - ledgers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - orchestrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - orchestrations/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - orchestrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - payments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - payments/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - payments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - reconciliations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - reconciliations/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - reconciliations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - resourcereferences
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - resourcereferences/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - resourcereferences/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - searches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - searches/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - searches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - settings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - settings/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - settings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - stargates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - stargates/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - stargates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - versions/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - versions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - wallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - wallets/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - wallets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - webhooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - configurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - configurations/finalizers
  verbs:
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - configurations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - migrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - migrations/finalizers
  verbs:
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - migrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - stacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - stacks/finalizers
  verbs:
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - stacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - versions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stack.formance.com
  resources:
  - versions/finalizers
  verbs:
  - update
- apiGroups:
  - stack.formance.com
  resources:
  - versions/status
  verbs:
  - get
  - patch
  - update
