issuer: http://localhost:5556/dex

storage:
  type: memory

frontend:
  issuer: Formance
  dir: /app/web
  theme: formance

web:
  http: 0.0.0.0:5556

telemetry:
  http: 0.0.0.0:5558

grpc:
  addr: 0.0.0.0:5557

oauth2:
  skipApprovalScreen: true
  responseTypes:
    - code
    - token
    - id_token

staticClients:
  - id: gateway
    redirectURIs:
      - 'http://localhost:8080/authorize/callback'
    name: 'Auth Gateway'
    secret: ZXhhbXBsZS1hcHAtc2VjcmV0

enablePasswordDB: true

staticPasswords:
  - email: 'user1@orga1.com'
    username: 'user1'
    userID: '00000000-0000-0000-0000-000000000011'
    hash: '$2y$10$z6QSp/RU./kG6z3IauPaF.qDjRfkOIuP2dx5xb8GGvU/uBzU7wTEC' # user1
  - email: 'user2@orga1.com'
    hash: '$2y$10$VDnbwmixVIV9ZG3Z8BkomOgakiJ6WyYDQY.x3Tpxu2.qHrWCFaU6q' # user2
    username: 'user2'
    userID: '00000000-0000-0000-0000-000000000012'
  - email: 'user1@orga2.com'
    username: 'user1'
    userID: '00000000-0000-0000-0000-000000000021'
    hash: '$2y$10$z6QSp/RU./kG6z3IauPaF.qDjRfkOIuP2dx5xb8GGvU/uBzU7wTEC' # user1
  - email: 'user2@orga2.com'
    hash: '$2y$10$VDnbwmixVIV9ZG3Z8BkomOgakiJ6WyYDQY.x3Tpxu2.qHrWCFaU6q' # user2
    username: 'user2'
    userID: '00000000-0000-0000-0000-000000000022'

connectors:
  - type: github
    # Required field for connector id.
    id: github
    # Required field for connector name.
    name: GitHub
    config:
      # Credentials can be string literals or pulled from the environment.
      clientID: $GITHUB_CLIENT_ID
      clientSecret: $GITHUB_CLIENT_SECRET
      redirectURI: http://localhost:5556/dex/callback
  - type: oidc
    id: Formance
    name: Formance
    config:
      # Canonical URL of the provider, also used for configuration discovery.
      # This value MUST match the value returned in the provider config discovery.
      #
      # See: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig
      issuer: https://accounts.google.com

      # Connector config values starting with a "$" will read from the environment.
      clientID: $GOOGLE_CLIENT_ID
      clientSecret: $GOOGLE_CLIENT_SECRET

      # Dex's issuer URL + "/callback"
      redirectURI: http://localhost:5556/dex/callback
