image:
  pullPolicy: Always

debug: true

server:
  address: ""
  tls:
    enabled: true
    insecureSkipVerify: true

agent:
  id: "b7549a16-f74a-4815-ab1e-bb8ef1c3833b"
  baseUrl: ""
  production: false
  # Authentication token
  authentication:
    mode: token
    token: abcd
