---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: default-postgres-uri
spec:
  key: postgres.*.uri
  stacks:
    - '*'
  value: postgresql://postgres-postgresql.formance.svc.cluster.local:5432?disableSSLMode=true&secret=postgres
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: default-broker
spec:
  key: broker.dsn
  stacks:
    - '*'
  value: nats://nats.default.svc.cluster.local:4222?replicas=1
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: default-payments-encryption-key
spec:
  key: payments.encryption-key
  stacks:
    - '*'
  value: default-encryption-key
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: default-elasticsearch-dsn
spec:
  key: elasticsearch.dsn
  stacks:
    - '*'
  value: http://elasticsearch-master.formance.svc.cluster.local:9200?secret=elasticsearch
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: default-temporal-dsn
spec:
  stacks:
    - '*'
  key: temporal.dsn
  value: temporal://local-operator.sihc8.tmprl.cloud:7233/local-operator.sihc8?secret=temporal
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: stacks-temporal-dsn
spec:
  stacks:
    - '*'
  key: default-otlp
  value: grpc://otel-collector-opentelemetry-collector.formance.svc.cluster.local:4317?insecure=true
---
apiVersion: formance.com/v1beta1
kind: Settings
metadata:
  name: clear-database
spec:
  stacks:
    - '*'
  key: clear-database
  value: "true"