apiVersion: v2
name: agent
description: Formance Membership Agent Helm Chart
home: "https://formance.com"
sources:
- "https://github.com/formancehq/membership-api"
maintainers:
- name: "Formance Team"
  email: "support@formance.com"
icon: "https://avatars.githubusercontent.com/u/84325077?s=200&v=4"

type: application
version: 0.1.1
appVersion: "latest"
