on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
      count:
        required: false
        default: '10'
        type: string
      duration:
        required: false
        default: 30s
        type: string
      branch:
        required: false
        default: 'pr'
        type: string

jobs:
  benchmarks:
    runs-on: formance-runner
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Configurating go
      uses: actions/setup-go@v3
      with:
        go-version-file: ./components/ledger/go.mod
        cache-dependency-path: ./components/ledger/go.sum
        cache: true
    - name: Run benchmarks
      run: task ledger:bench:${{ inputs.mode }} BRANCH=${{ inputs.branch }} COUNT=${{ inputs.count }} DURATION=${{ inputs.duration }} --exit-code
    - uses: actions/upload-artifact@v3
      with:
        name: benchmarks-${{ inputs.mode }}
        path: components/ledger/benchs/*.stats
